{% set name = "unzip-http" %}
{% set version = "0.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/unzip-http-{{ version }}.tar.gz
  sha256: 60b673292b2069a64991744a890f10193c79f43df12df7553c4dea42483c3391

build:
  skip: true  # [py<38]
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - pip
    - python
  run:
    - python
    - urllib3

test:
  imports:
    - unzip_http
  commands:
    - unzip-http
  requires:
    - pip

about:
  home: https://github.com/saulpw/unzip-http
  summary: extract files from .zip files over http without downloading entire archive
  license: MIT
  license_file: LICENSE-mit.txt

extra:
  recipe-maintainers:
    - gforsyth
    - anjakefala
